### ISSUE TITLE
ImportError: cannot import name 'vincenty' from 'geopy.distance'

### ISSUE THREAD

**Issue by bguerr** [usgs/slab2#12]
Hello!

I am trying to create an input file but the following error appears while typing
                   _python s2d.py -p alu -d ~/Escritorio/slab2-master/1219database -f alu_12-19_input.csv_
in [slab2folder]/slab2code:
 
**Traceback (most recent call last):
  File "s2d.py", line 12, in <module>
    from s2d_fnctns import *
  File "/home/benjamin/Escritorio/slab2-master/slab2code/s2d_fnctns.py", line 11, in <module>
    from geopy.distance import vincenty
ImportError: cannot import name 'vincenty' from 'geopy.distance' (/home/benjamin/anaconda3/envs/slab2env/lib/python3.7/site-packages/geopy/distance.py)**

Typing _python s2d.py -h_ or _python s2d_fnctns.py -h_ throws a similar error.

Cheers,
Benjamín

**Comment by khaynie-usgs** [comment]
Hi @bguerr! Sorry for the extremely late response. The fix is to change from `geopy.distance import vincenty` to from `geopy.distance import geodesic`. This has been updated in s2d.py. I hope you were able to fix it on your own! Please reach out if there is anything else I can help you with.
